const fs = require('fs');
let code = fs.readFileSync('src/App.tsx', 'utf8');

const oldRegex = /function pdf_export\(\) \{[\s\S]*?\n\}/;

const newExport = `async function pdf_export() {
  const results = document.getElementById('results-area');
  if (!results) return;

  const btn = document.getElementById('pdf-export-btn');
  if (btn) btn.style.display = 'none';

  const printDiv = document.createElement('div');
  printDiv.id = 'print-container';
  printDiv.style.position = 'absolute';
  printDiv.style.top = '-9999px';
  printDiv.style.left = '0';
  printDiv.style.width = '800px';
  printDiv.style.backgroundColor = '#ffffff';
  printDiv.style.fontFamily = "'Segoe UI', sans-serif";
  printDiv.style.color = '#1a3330';
  printDiv.style.padding = '40px';
  
  printDiv.innerHTML = \\\`
    <div style="text-align: center; border-bottom: 2px solid #4A7C6F; padding-bottom: 20px; margin-bottom: 24px;">
      <div style="font-size: 2.5rem; margin-bottom: 8px; font-family: sans-serif;">💊</div>
      <div style="font-size: 1.8rem; font-weight: 700; color: #4A7C6F;">MediScan</div>
      <div>Prescription Analysis Report</div>
      <div style="font-size: 13px; color: #6b9490; margin-top: 6px;">
        Generated: \\\${new Date().toLocaleDateString('en-US', {
          year:'numeric', month:'long', day:'numeric',
          hour:'2-digit', minute:'2-digit'
        })}
      </div>
    </div>
    <div id="pdf-content-wrapper" style="font-size: 14px;">
      \\\${results.innerHTML}
    </div>
    <div style="text-align: center; font-size: 11px; color: #6b9490; border-top: 1px solid #e2e8f0; padding-top: 16px; margin-top: 32px;">
      Generated by MediScan App<br/>
      ⚕️ This report is for educational purposes only.
      Always consult your doctor or pharmacist.
    </div>
  \\\`;
  document.body.appendChild(printDiv);
  
  // hide annoying things inside the cloned HTML
  const innerBtn = printDiv.querySelector('.print\\\\:hidden');
  if (innerBtn) innerBtn.style.display = 'none';
  const innerBtns = printDiv.querySelectorAll('button');
  innerBtns.forEach(b => b.style.display = 'none');

  try {
    const canvas = await html2canvas(printDiv, { scale: 2, useCORS: true, logging: false });
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });
    
    // A4 dimensions: 210 x 297 mm
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
    
    let heightLeft = pdfHeight;
    let position = 0;
    const pageHeight = pdf.internal.pageSize.getHeight();
    
    // Add first page
    pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, pdfHeight);
    heightLeft -= pageHeight;
    
    // Add subsequent pages if needed
    while (heightLeft >= 0) {
      position = heightLeft - pdfHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, pdfHeight);
      heightLeft -= pageHeight;
    }
    
    pdf.save('prescription_report.pdf');
  } catch (err) {
    console.error("PDF generation failed", err);
  } finally {
    document.body.removeChild(printDiv);
    if (btn) btn.style.display = '';
  }
}`;

if (oldRegex.test(code)) {
  code = code.replace(oldRegex, newExport);
  fs.writeFileSync('src/App.tsx', code);
  console.log("Successfully replaced pdf_export");
} else {
  console.log("Could not find pdf_export");
}
